name: dynamic-scheduler
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask
  - pip
  - pip:
      - react
      - firebase-admin
      - pymongo
      - flask-cors
      - nltk
      - numpy
      - mui
